---
- name: Converge
  hosts: all
  become: true

  vars:
    ansible_become_password: ansible

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: olidrouin.packer_rhel
